parameters:
    orocrm_abandonedcart.form.type.abandonedcart_list.class: OroCRM\Bundle\AbandonedCartBundle\Form\Type\AbandonedCartListType

    orocrm_abandonedcart.form.handler.abandonedcart_campaign.class: OroCRM\Bundle\AbandonedCartBundle\Form\Handler\AbandonedCartCampaignHandler
    orocrm_abandonedcart.campaign_factory.class: OroCRM\Bundle\AbandonedCartBundle\Model\AbandonedCartList\CampaignFactory
    orocrm_abandonedcart.abandonedcart_campaign_factory.class: OroCRM\Bundle\AbandonedCartBundle\Model\AbandonedCartList\AbandonedCartCampaignFactory

    orocrm_abandonedcart.form.type.conversion.class: OroCRM\Bundle\AbandonedCartBundle\Form\Type\AbandonedCartConversionType
    orocrm_abandonedcart.form.handler.conversion_form.class: OroCRM\Bundle\AbandonedCartBundle\Form\Handler\ConversionFormHandler

services:
    # AbandonedCartList
    orocrm_abandonedcart_list.form.type.abandonedcart_list:
        class: %orocrm_abandonedcart.form.type.abandonedcart_list.class%
        arguments:
            - %orocrm_magento.entity.cart.class%
            - %orocrm_abandonedcart.entity.marketing_list_type.class%
            - %orocrm_marketing_list.entity.class%
        tags:
            - { name: form.type, alias: orocrm_abandonedcart_list }

    orocrm_abandonedcart_list.form.abandonedcart_list:
        class:           Symfony\Component\Form\Form
        factory_method:  createNamed
        factory_service: form.factory
        arguments:
            - "orocrm_abandonedcart_list_form"
            - "orocrm_abandonedcart_list"

    orocrm_abandonedcart.campaign_factory:
        class: %orocrm_abandonedcart.campaign_factory.class%

    orocrm_abandonedcart.abandonedcart_campaign_factory:
        class: %orocrm_abandonedcart.abandonedcart_campaign_factory.class%
        arguments:
            - "@orocrm_abandonedcart.campaign_factory"

    orocrm_abandonedcart.form.handler.abandonedcart_campaign:
        class: %orocrm_abandonedcart.form.handler.abandonedcart_campaign.class%
        scope: request
        arguments:
            - "@orocrm_abandonedcart_list.form.abandonedcart_list"
            - "@request"
            - "@doctrine"
            - "@validator"
            - "@translator"
            - "@orocrm_abandonedcart.abandonedcart_campaign_factory"
            - "@orocrm_abandonedcart.provider"

    orocrm_abandonedcart.form.type.conversion:
        class: %orocrm_abandonedcart.form.type.conversion.class%
        arguments:
            - "@orocrm_abandonedcart.conversion_manager"
            - %orocrm_mailchimp.entity.campaign.class%
        tags:
            - { name: form.type, alias: "orocrm_abandonedcart_conversion" }

    orocrm_abandonedcart.form.conversion:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["orocrm_abandonedcart_conversion", "orocrm_abandonedcart_conversion", null]

    orocrm_abandonedcart.form.handler.conversion_form:
        class: %orocrm_abandonedcart.form.handler.conversion_form.class%
        scope: request
        arguments: ["@orocrm_abandonedcart.form.conversion", "@request", "@doctrine.orm.entity_manager"]

