parameters:
    oro_abandonedcart.form.type.abandonedcart_list.class: Oro\Bundle\AbandonedCartBundle\Form\Type\AbandonedCartListType

    oro_abandonedcart.form.handler.abandonedcart_campaign.class: Oro\Bundle\AbandonedCartBundle\Form\Handler\AbandonedCartCampaignHandler
    oro_abandonedcart.campaign_factory.class: Oro\Bundle\AbandonedCartBundle\Model\AbandonedCartList\CampaignFactory
    oro_abandonedcart.abandonedcart_campaign_factory.class: Oro\Bundle\AbandonedCartBundle\Model\AbandonedCartList\AbandonedCartCampaignFactory

    oro_abandonedcart.form.type.conversion.class: Oro\Bundle\AbandonedCartBundle\Form\Type\AbandonedCartConversionType
    oro_abandonedcart.form.handler.conversion_form.class: Oro\Bundle\AbandonedCartBundle\Form\Handler\ConversionFormHandler

services:
    # AbandonedCartList
    oro_abandonedcart_list.form.type.abandonedcart_list:
        class: %oro_abandonedcart.form.type.abandonedcart_list.class%
        arguments:
            - %oro_magento.entity.cart.class%
            - %oro_abandonedcart.entity.marketing_list_type.class%
            - %oro_marketing_list.entity.class%
        tags:
            - { name: form.type, alias: oro_abandonedcart_list }

    oro_abandonedcart_list.form.abandonedcart_list:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments:
            - "oro_abandonedcart_list_form"
            - "oro_abandonedcart_list"

    oro_abandonedcart.campaign_factory:
        class: %oro_abandonedcart.campaign_factory.class%

    oro_abandonedcart.abandonedcart_campaign_factory:
        class: %oro_abandonedcart.abandonedcart_campaign_factory.class%
        arguments:
            - "@oro_abandonedcart.campaign_factory"

    oro_abandonedcart.form.handler.abandonedcart_campaign:
        class: %oro_abandonedcart.form.handler.abandonedcart_campaign.class%
        arguments:
            - "@oro_abandonedcart_list.form.abandonedcart_list"
            - "@request_stack"
            - "@doctrine"
            - "@validator"
            - "@translator"
            - "@oro_abandonedcart.abandonedcart_campaign_factory"
            - "@oro_abandonedcart.provider"

    oro_abandonedcart.form.type.conversion:
        class: %oro_abandonedcart.form.type.conversion.class%
        arguments:
            - "@oro_abandonedcart.conversion_manager"
            - %oro_mailchimp.entity.campaign.class%
        tags:
            - { name: form.type, alias: "oro_abandonedcart_conversion" }

    oro_abandonedcart.form.conversion:
        class: Symfony\Component\Form\Form
        factory: ['@form.factory', createNamed]
        arguments: ["oro_abandonedcart_conversion", "oro_abandonedcart_conversion", null]

    oro_abandonedcart.form.handler.conversion_form:
        class: %oro_abandonedcart.form.handler.conversion_form.class%
        arguments: ["@oro_abandonedcart.form.conversion", "@request_stack", "@doctrine.orm.entity_manager"]

