channels:
   entity_data:
       -
          name: Oro\Bundle\AbandonedCartBundle\Entity\AbandonedCartCampaign
          dependent:
              - OroCRM\Bundle\MagentoBundle\Entity\Cart
          navigation_items:
              - application_menu.marketing_tab.abandoned_cart_list

   channel_types:
        magento:
            entities:
                - Oro\Bundle\AbandonedCartBundle\Entity\AbandonedCartCampaign
