navigation:
    menu_config:
        items:
            abandoned_cart_list:
                label: 'oro.abandonedcart.abandonedcartcampaign.entity_plural_label'
                route: 'oro_abandoned_cart_list'
                display: false
                position: 10
                extras:
                    routes: ['oro_abandoned_cart_list_*']
        tree:
            application_menu:
                children:
                    marketing_tab:
                        children:
                            abandoned_cart_list: ~

    titles:
        oro_abandoned_cart_list:  ~
        oro_abandoned_cart_list_view: '%%entityName%%'
        oro_abandoned_cart_list_update: %%entityName%% - oro.ui.edit
        oro_abandoned_cart_list_create: oro.ui.create_entity
