placeholders:
    placeholders:
        abandoned_cart_mailchimp_menu:
            items:
                oro_mailchimp_abandoned_cart_buttons: ~

    items:
        oro_mailchimp_abandoned_cart_buttons:
            action: OroCRMAbandonedCartBundle:AbandonedCart:connectionButtons
            applicable: "@oro_mailchimp.placeholder.filter.buttons_filder->isApplicable($entity$)"

